[programs.localnet]
s3_dapp_solana = "DBKpaRbYwPjES1PuP933hjLQkzDiubo5NjNoXt4nv3Zq"
game_rule_v2 = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/kiet.huynh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
